management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  tomcat:
    threads:
      max: 1000


# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 192.168.31.241:9876
  producer:
    #生产者group名称
    group: producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2



